version: 2.1

orbs:
  node: circleci/node@1.0.1
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  build:
    executor:
      name: node/default
      tag: 8.15.1
    working_directory: ~/project
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install dependency
                command: yarn
          cache-key: yarn.lock
      - run:
          name: Build
          command: ./bin/build.sh
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    executor: aws-cli/default
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: .
      - aws-cli/install
      - run:
          name: Deploy
          command: ./bin/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
